const fs = require('fs');

const serverFile = '/home/ubuntu/booyah-backend/server.js';
let content = fs.readFileSync(serverFile, 'utf8');

const matches = [
  // 1. FREE TOURNAMENTS (Ad Coins) - Clean 0 slots
  {
    id: 'FREE-BR-01',
    title: '🆓 Free Fire BR Solo (Ad Coins)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'free',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'bermuda',
    entryFeeType: 'adCoins',
    entryFee: 5,
    prizePool: {
      totalPool: 50,
      firstPlace: 25,
      secondPlace: 15,
      thirdPlace: 10,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 2
    },
    maxSlots: 48,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },
  {
    id: 'FREE-CS-01',
    title: '🆓 Free Fire CS 4v4 Squad (Ad Coins)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'free',
    mode: 'cs',
    teamType: 'squad',
    matchFormat: 'cs4v4',
    map: 'bermuda',
    entryFeeType: 'adCoins',
    entryFee: 2,
    prizePool: {
      totalPool: 20,
      firstPlace: 20,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 8,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 7200000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },
  {
    id: 'FREE-LW-01',
    title: '🆓 Lone Wolf 1v1 Battle (Ad Coins)',
    bannerUrl: 'https://i.ibb.co/9ktcjYSX/lonewolfhomescreen.png',
    gameType: 'freeFire',
    matchType: 'free',
    mode: 'loneWolf',
    teamType: 'solo',
    matchFormat: 'loneWolf1v1',
    map: 'ironCage',
    entryFeeType: 'adCoins',
    entryFee: 2,
    prizePool: {
      totalPool: 10,
      firstPlace: 10,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 2,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 5400000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },

  // 2. 12 PAID DAILY TOURNAMENTS (Clean 0 slots, Unique Match IDs)
  // A. Battle Royale (4 Matches)
  {
    id: 'FF-BR-101',
    title: 'BR Solo Quick Cup (₹10 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 10,
    prizePool: {
      totalPool: 360,
      firstPlace: 180,
      secondPlace: 100,
      thirdPlace: 80,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 5
    },
    maxSlots: 48,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 1800000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },
  {
    id: 'FF-BR-102',
    title: 'BR Solo Pro Championship (₹20 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'purgatory',
    entryFeeType: 'cash',
    entryFee: 20,
    prizePool: {
      totalPool: 720,
      firstPlace: 360,
      secondPlace: 220,
      thirdPlace: 140,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 10
    },
    maxSlots: 48,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 4500000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },
  {
    id: 'FF-BR-103',
    title: 'BR Elite Masters (₹50 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'kalahari',
    entryFeeType: 'cash',
    entryFee: 50,
    prizePool: {
      totalPool: 1800,
      firstPlace: 900,
      secondPlace: 540,
      thirdPlace: 360,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 25
    },
    maxSlots: 48,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 9000000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },
  {
    id: 'FF-BR-104',
    title: 'BR High Roller Grand Slam (₹100 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 100,
    prizePool: {
      totalPool: 3600,
      firstPlace: 1800,
      secondPlace: 1100,
      thirdPlace: 700,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 50
    },
    maxSlots: 48,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 14400000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },

  // B. Clash Squad (4 Matches)
  {
    id: 'FF-CS-201',
    title: 'CS 4v4 Squad Clash (₹10 Entry)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'cs',
    teamType: 'squad',
    matchFormat: 'cs4v4',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 10,
    prizePool: {
      totalPool: 60,
      firstPlace: 60,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 8,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 2700000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },
  {
    id: 'FF-CS-202',
    title: 'CS 4v4 Squad Showdown (₹20 Entry)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'cs',
    teamType: 'squad',
    matchFormat: 'cs4v4',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 20,
    prizePool: {
      totalPool: 120,
      firstPlace: 120,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 8,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 6300000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },
  {
    id: 'FF-CS-203',
    title: 'CS 4v4 Squad Masters (₹50 Entry)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'cs',
    teamType: 'squad',
    matchFormat: 'cs4v4',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 50,
    prizePool: {
      totalPool: 300,
      firstPlace: 300,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 8,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 10800000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },
  {
    id: 'FF-CS-204',
    title: 'CS 4v4 Champions League (₹100 Entry)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'cs',
    teamType: 'squad',
    matchFormat: 'cs4v4',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 100,
    prizePool: {
      totalPool: 600,
      firstPlace: 600,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 8,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 15000000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },

  // C. Lone Wolf 1v1 (4 Matches)
  {
    id: 'FF-LW-301',
    title: 'Lone Wolf 1v1 Dual (₹10 Entry)',
    bannerUrl: 'https://i.ibb.co/9ktcjYSX/lonewolfhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'loneWolf',
    teamType: 'solo',
    matchFormat: 'loneWolf1v1',
    map: 'ironCage',
    entryFeeType: 'cash',
    entryFee: 10,
    prizePool: {
      totalPool: 15,
      firstPlace: 15,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 2,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 1200000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },
  {
    id: 'FF-LW-302',
    title: 'Lone Wolf 1v1 Battle (₹20 Entry)',
    bannerUrl: 'https://i.ibb.co/9ktcjYSX/lonewolfhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'loneWolf',
    teamType: 'solo',
    matchFormat: 'loneWolf1v1',
    map: 'ironCage',
    entryFeeType: 'cash',
    entryFee: 20,
    prizePool: {
      totalPool: 30,
      firstPlace: 30,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 2,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3000000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },
  {
    id: 'FF-LW-303',
    title: 'Lone Wolf 1v1 Masters (₹50 Entry)',
    bannerUrl: 'https://i.ibb.co/9ktcjYSX/lonewolfhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'loneWolf',
    teamType: 'solo',
    matchFormat: 'loneWolf1v1',
    map: 'ironCage',
    entryFeeType: 'cash',
    entryFee: 50,
    prizePool: {
      totalPool: 75,
      firstPlace: 75,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 2,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 6000000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },
  {
    id: 'FF-LW-304',
    title: 'Lone Wolf 1v1 Grand Slam (₹100 Entry)',
    bannerUrl: 'https://i.ibb.co/9ktcjYSX/lonewolfhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'loneWolf',
    teamType: 'solo',
    matchFormat: 'loneWolf1v1',
    map: 'ironCage',
    entryFeeType: 'cash',
    entryFee: 100,
    prizePool: {
      totalPool: 150,
      firstPlace: 150,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 2,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 12000000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },

  // 3. SPECIAL TOURNAMENTS (Mega Sunday & Jackpot)
  {
    id: 'MEGA-SUN-500',
    title: '👑 Sunday Mega Championship (₹500 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 500,
    prizePool: {
      totalPool: 18000,
      firstPlace: 9000,
      secondPlace: 5400,
      thirdPlace: 3600,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 150
    },
    maxSlots: 48,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 86400000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  },
  {
    id: 'JACKPOT-1000',
    title: '🏆 Monthly Grand Jackpot (₹1000 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 1000,
    prizePool: {
      totalPool: 36000,
      firstPlace: 18000,
      secondPlace: 10800,
      thirdPlace: 7200,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 300
    },
    maxSlots: 48,
    filledSlots: 0,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 172800000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false,
    hostName: 'Booyah Esports Official'
  }
];

// Update matches array in server.js
const dbMatchesRegex = /matches:\s*\[([\s\S]*?)\],\s*users:/;
if (dbMatchesRegex.test(content)) {
  content = content.replace(dbMatchesRegex, `matches: ${JSON.stringify(matches, null, 2)},\n  users:`);
  fs.writeFileSync(serverFile, content, 'utf8');
  console.log('Successfully reseeded server.js default matches!');
}

// Also update data/db.json if it exists
const dbJsonPath = '/home/ubuntu/booyah-backend/data/db.json';
if (fs.existsSync(dbJsonPath)) {
  try {
    const dbData = JSON.parse(fs.readFileSync(dbJsonPath, 'utf8'));
    dbData.matches = matches;
    fs.writeFileSync(dbJsonPath, JSON.stringify(dbData, null, 2), 'utf8');
    console.log('Successfully updated data/db.json matches directly!');
  } catch (err) {
    console.error('Error updating db.json:', err);
  }
}
