const fs = require('fs');

const serverFile = '/home/ubuntu/booyah-backend/server.js';
let content = fs.readFileSync(serverFile, 'utf8');

const matches = [
  // 1. FREE TOURNAMENTS (Ad Coins)
  {
    id: 'match_free_br_01',
    title: '🆓 Free Fire BR Solo (Ad Coins)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'free',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'bermuda',
    entryFeeType: 'adCoins',
    entryFee: 5,
    prizePool: {
      totalPool: 50,
      firstPlace: 25,
      secondPlace: 15,
      thirdPlace: 10,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 2
    },
    maxSlots: 48,
    filledSlots: 14,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3600000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },
  {
    id: 'match_free_cs_01',
    title: '🆓 Free Fire CS 4v4 Squad (Ad Coins)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'free',
    mode: 'cs',
    teamType: 'squad',
    matchFormat: 'cs4v4',
    map: 'bermuda',
    entryFeeType: 'adCoins',
    entryFee: 2,
    prizePool: {
      totalPool: 20,
      firstPlace: 20,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 8,
    filledSlots: 4,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 7200000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },
  {
    id: 'match_free_lw_01',
    title: '🆓 Lone Wolf 1v1 Battle (Ad Coins)',
    bannerUrl: 'https://i.ibb.co/9ktcjYSX/lonewolfhomescreen.png',
    gameType: 'freeFire',
    matchType: 'free',
    mode: 'loneWolf',
    teamType: 'solo',
    matchFormat: 'loneWolf1v1',
    map: 'ironCage',
    entryFeeType: 'adCoins',
    entryFee: 2,
    prizePool: {
      totalPool: 10,
      firstPlace: 10,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 2,
    filledSlots: 1,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 5400000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },

  // 2. PAID TOURNAMENTS (Battle Royale)
  {
    id: 'match_br_10_01',
    title: 'BR Solo Quick Cup (₹10 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 10,
    prizePool: {
      totalPool: 360,
      firstPlace: 180,
      secondPlace: 100,
      thirdPlace: 80,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 5
    },
    maxSlots: 48,
    filledSlots: 22,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 1800000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },
  {
    id: 'match_br_20_01',
    title: 'BR Solo Pro Championship (₹20 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'purgatory',
    entryFeeType: 'cash',
    entryFee: 20,
    prizePool: {
      totalPool: 720,
      firstPlace: 360,
      secondPlace: 220,
      thirdPlace: 140,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 10
    },
    maxSlots: 48,
    filledSlots: 31,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 4500000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },
  {
    id: 'match_br_50_01',
    title: 'BR Elite Masters (₹50 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'kalahari',
    entryFeeType: 'cash',
    entryFee: 50,
    prizePool: {
      totalPool: 1800,
      firstPlace: 900,
      secondPlace: 540,
      thirdPlace: 360,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 25
    },
    maxSlots: 48,
    filledSlots: 18,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 9000000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },
  {
    id: 'match_br_100_01',
    title: 'BR High Roller Grand Slam (₹100 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 100,
    prizePool: {
      totalPool: 3600,
      firstPlace: 1800,
      secondPlace: 1100,
      thirdPlace: 700,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 50
    },
    maxSlots: 48,
    filledSlots: 15,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 14400000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },

  // 3. CLASH SQUAD (4v4)
  {
    id: 'match_cs_10_01',
    title: 'CS 4v4 Squad Clash (₹10 Entry)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'cs',
    teamType: 'squad',
    matchFormat: 'cs4v4',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 10,
    prizePool: {
      totalPool: 60,
      firstPlace: 60,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 8,
    filledSlots: 6,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 2700000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },
  {
    id: 'match_cs_20_01',
    title: 'CS 4v4 Squad Showdown (₹20 Entry)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'cs',
    teamType: 'squad',
    matchFormat: 'cs4v4',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 20,
    prizePool: {
      totalPool: 120,
      firstPlace: 120,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 8,
    filledSlots: 4,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 6300000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },
  {
    id: 'match_cs_50_01',
    title: 'CS 4v4 Squad Masters (₹50 Entry)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'cs',
    teamType: 'squad',
    matchFormat: 'cs4v4',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 50,
    prizePool: {
      totalPool: 300,
      firstPlace: 300,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 8,
    filledSlots: 2,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 10800000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },

  // 4. LONE WOLF (1v1)
  {
    id: 'match_lw_10_01',
    title: 'Lone Wolf 1v1 Dual (₹10 Entry)',
    bannerUrl: 'https://i.ibb.co/9ktcjYSX/lonewolfhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'loneWolf',
    teamType: 'solo',
    matchFormat: 'loneWolf1v1',
    map: 'ironCage',
    entryFeeType: 'cash',
    entryFee: 10,
    prizePool: {
      totalPool: 15,
      firstPlace: 15,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 2,
    filledSlots: 1,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 1200000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },
  {
    id: 'match_lw_20_01',
    title: 'Lone Wolf 1v1 Battle (₹20 Entry)',
    bannerUrl: 'https://i.ibb.co/9ktcjYSX/lonewolfhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'loneWolf',
    teamType: 'solo',
    matchFormat: 'loneWolf1v1',
    map: 'ironCage',
    entryFeeType: 'cash',
    entryFee: 20,
    prizePool: {
      totalPool: 30,
      firstPlace: 30,
      secondPlace: 0,
      thirdPlace: 0,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 0
    },
    maxSlots: 2,
    filledSlots: 1,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 3000000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },

  // 5. MEGA SPECIALS
  {
    id: 'match_mega_sunday_500',
    title: '👑 Sunday Mega Championship (₹500 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 500,
    prizePool: {
      totalPool: 18000,
      firstPlace: 9000,
      secondPlace: 5400,
      thirdPlace: 3600,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 150
    },
    maxSlots: 48,
    filledSlots: 42,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 86400000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  },
  {
    id: 'match_monthly_jackpot_1000',
    title: '🏆 Monthly Grand Jackpot (₹1000 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    matchFormat: 'solo',
    map: 'bermuda',
    entryFeeType: 'cash',
    entryFee: 1000,
    prizePool: {
      totalPool: 36000,
      firstPlace: 18000,
      secondPlace: 10800,
      thirdPlace: 7200,
      fourthPlace: 0,
      fifthPlace: 0,
      perKill: 300
    },
    maxSlots: 48,
    filledSlots: 36,
    status: 'upcoming',
    matchTime: new Date(Date.now() + 172800000).toISOString(),
    credentials: { roomId: '', roomPassword: '', isRevealed: false },
    participants: [],
    registeredTeams: [],
    hasUserWatchedAdToUnlockRoom: false
  }
];

// Update matches array in db
const dbMatchesRegex = /matches:\s*\[([\s\S]*?)\],\s*users:/;
if (dbMatchesRegex.test(content)) {
  content = content.replace(dbMatchesRegex, `matches: ${JSON.stringify(matches, null, 2)},\n  users:`);
  fs.writeFileSync(serverFile, content, 'utf8');
  console.log('Matches successfully reseeded in server.js with full PrizePool schema');
} else {
  console.log('Could not find matches block');
}
