const fs = require('fs');

const serverFile = '/home/ubuntu/booyah-backend/server.js';
let content = fs.readFileSync(serverFile, 'utf8');

const matches = [
  // 1. FREE TOURNAMENTS (Ad Coins)
  {
    id: 'match_free_br_01',
    title: '🆓 Free Fire BR Solo (Ad Coins)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'free',
    mode: 'br',
    teamType: 'solo',
    map: 'bermuda',
    entryFee: 5,
    prizePool: 50,
    firstPrize: 25,
    secondPrize: 15,
    thirdPrize: 10,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 2,
    maxSlots: 48,
    filledSlots: 14,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 3600000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },
  {
    id: 'match_free_cs_01',
    title: '🆓 Free Fire CS 4v4 Squad (Ad Coins)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'free',
    mode: 'cs',
    teamType: 'squad',
    map: 'bermuda',
    entryFee: 2,
    prizePool: 20,
    firstPrize: 20,
    secondPrize: 0,
    thirdPrize: 0,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 0,
    maxSlots: 8,
    filledSlots: 4,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 7200000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },
  {
    id: 'match_free_lw_01',
    title: '🆓 Lone Wolf 1v1 Battle (Ad Coins)',
    bannerUrl: 'https://i.ibb.co/9ktcjYSX/lonewolfhomescreen.png',
    gameType: 'freeFire',
    matchType: 'free',
    mode: 'loneWolf',
    teamType: 'solo',
    map: 'ironCage',
    entryFee: 2,
    prizePool: 10,
    firstPrize: 10,
    secondPrize: 0,
    thirdPrize: 0,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 0,
    maxSlots: 2,
    filledSlots: 1,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 5400000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },

  // 2. PAID TOURNAMENTS (Battle Royale)
  {
    id: 'match_br_10_01',
    title: 'BR Solo Quick Cup (₹10 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    map: 'bermuda',
    entryFee: 10,
    prizePool: 360,
    firstPrize: 180,
    secondPrize: 100,
    thirdPrize: 80,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 5,
    maxSlots: 48,
    filledSlots: 22,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 1800000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },
  {
    id: 'match_br_20_01',
    title: 'BR Solo Pro Championship (₹20 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    map: 'purgatory',
    entryFee: 20,
    prizePool: 720,
    firstPrize: 360,
    secondPrize: 220,
    thirdPrize: 140,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 10,
    maxSlots: 48,
    filledSlots: 31,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 4500000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },
  {
    id: 'match_br_50_01',
    title: 'BR Elite Masters (₹50 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    map: 'kalahari',
    entryFee: 50,
    prizePool: 1800,
    firstPrize: 900,
    secondPrize: 540,
    thirdPrize: 360,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 25,
    maxSlots: 48,
    filledSlots: 18,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 9000000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },
  {
    id: 'match_br_100_01',
    title: 'BR High Roller Grand Slam (₹100 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    map: 'bermuda',
    entryFee: 100,
    prizePool: 3600,
    firstPrize: 1800,
    secondPrize: 1100,
    thirdPrize: 700,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 50,
    maxSlots: 48,
    filledSlots: 15,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 14400000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },

  // 3. CLASH SQUAD (4v4)
  {
    id: 'match_cs_10_01',
    title: 'CS 4v4 Squad Clash (₹10 Entry)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'cs',
    teamType: 'squad',
    map: 'bermuda',
    entryFee: 10,
    prizePool: 60,
    firstPrize: 60,
    secondPrize: 0,
    thirdPrize: 0,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 0,
    maxSlots: 8,
    filledSlots: 6,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 2700000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },
  {
    id: 'match_cs_20_01',
    title: 'CS 4v4 Squad Showdown (₹20 Entry)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'cs',
    teamType: 'squad',
    map: 'bermuda',
    entryFee: 20,
    prizePool: 120,
    firstPrize: 120,
    secondPrize: 0,
    thirdPrize: 0,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 0,
    maxSlots: 8,
    filledSlots: 4,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 6300000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },
  {
    id: 'match_cs_50_01',
    title: 'CS 4v4 Squad Masters (₹50 Entry)',
    bannerUrl: 'https://i.ibb.co/S4qX9RW5/cshomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'cs',
    teamType: 'squad',
    map: 'bermuda',
    entryFee: 50,
    prizePool: 300,
    firstPrize: 300,
    secondPrize: 0,
    thirdPrize: 0,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 0,
    maxSlots: 8,
    filledSlots: 2,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 10800000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },

  // 4. LONE WOLF (1v1)
  {
    id: 'match_lw_10_01',
    title: 'Lone Wolf 1v1 Dual (₹10 Entry)',
    bannerUrl: 'https://i.ibb.co/9ktcjYSX/lonewolfhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'loneWolf',
    teamType: 'solo',
    map: 'ironCage',
    entryFee: 10,
    prizePool: 15,
    firstPrize: 15,
    secondPrize: 0,
    thirdPrize: 0,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 0,
    maxSlots: 2,
    filledSlots: 1,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 1200000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },
  {
    id: 'match_lw_20_01',
    title: 'Lone Wolf 1v1 Battle (₹20 Entry)',
    bannerUrl: 'https://i.ibb.co/9ktcjYSX/lonewolfhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'loneWolf',
    teamType: 'solo',
    map: 'ironCage',
    entryFee: 20,
    prizePool: 30,
    firstPrize: 30,
    secondPrize: 0,
    thirdPrize: 0,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 0,
    maxSlots: 2,
    filledSlots: 1,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 3000000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },

  // 5. MEGA SPECIALS
  {
    id: 'match_mega_sunday_500',
    title: '👑 Sunday Mega Championship (₹500 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    map: 'bermuda',
    entryFee: 500,
    prizePool: 18000,
    firstPrize: 9000,
    secondPrize: 5400,
    thirdPrize: 3600,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 150,
    maxSlots: 48,
    filledSlots: 42,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 86400000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  },
  {
    id: 'match_monthly_jackpot_1000',
    title: '🏆 Monthly Grand Jackpot (₹1000 Entry)',
    bannerUrl: 'https://i.ibb.co/PvV4vz0X/brhomescreen.png',
    gameType: 'freeFire',
    matchType: 'paid',
    mode: 'br',
    teamType: 'solo',
    map: 'bermuda',
    entryFee: 1000,
    prizePool: 36000,
    firstPrize: 18000,
    secondPrize: 10800,
    thirdPrize: 7200,
    fourthPrize: 0,
    fifthPrize: 0,
    perKill: 300,
    maxSlots: 48,
    filledSlots: 36,
    status: 'upcoming',
    scheduleTime: new Date(Date.now() + 172800000).toISOString(),
    participants: [],
    registeredTeams: [],
    isFull: false
  }
];

// Update matches array in db
const dbMatchesRegex = /matches:\s*\[([\s\S]*?)\],\s*users:/;
if (dbMatchesRegex.test(content)) {
  content = content.replace(dbMatchesRegex, `matches: ${JSON.stringify(matches, null, 2)},\n  users:`);
  fs.writeFileSync(serverFile, content, 'utf8');
  console.log('Matches successfully reseeded in server.js');
} else {
  console.log('Could not find matches block');
}
